source 'https://rubygems.org'

gem 'puma'
gem 'sinatra'
gem 'erubi'
gem 'mysql2'
gem 'mysql2-cs-bind'

group :development do
  gem 'sinatra-contrib'
  gem 'rack-mini-profiler', '0.9.1', require: false
  gem 'memory_profiler'
  gem 'flamegraph'
  gem 'stackprof'
  gem 'rack-lineprof'
end
